[workspace]
resolver = "2"
members = [
    "common",
    "ecs_lib",
    "tictactoe_3d/api",
    "tictactoe_3d/client",
    "tictactoe_3d/server",
]

# [profile.dev.package."*"]
# opt-level = 3

# [profile.release]
# lto = "thin"
